NFC_Project/urls.py
from core.views import handler500, custom_admin_index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _


admin.site.index_title = "Website Managment"
admin.site.site_header = "Chipper Group"

urlpatterns = [
    path('admin/', custom_admin_index, name='custom_admin_index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('users.passwords.urls')),
    path('', include('cards.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = handler500

cards/urls.py
from django.urls import path

from . import views

app_name = "cards"


urlpatterns = [
    path(
        "",
        views.NFCCardListView.as_view(extra_context={"active": "dashboard"}),
        name="user_dashboard",
    ),
    path(
        "landingPage/<uidb64>/",
        views.NFCCardView.as_view(),
        name="landing_page",
    ),
    path(
        "card-update/<uidb64>/",
        views.NFCCardDetailView.as_view(extra_context={"active": "dashboard"}),
        name="card_detail",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-password/",
        views.NFCCardUpdateView.as_view(extra_context={"active": "dashboard"}),
        name="update_card_password",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-title/",
        views.NFCCardUpdateTitle.as_view(extra_context={"active": "dashboard"}),
        name="update_card_title",
    ),
    path("cards-link/<uidb64>/", views.link_new_card, name="link_new_card"),
    path("cards-add/", views.add_new_card, name="add_new_card"),
    path("check-password/<uidb64>/", views.check_password, name="check_password"),
    path("card-update/update-business-card/<uidb64>/", views.update_business_card, name="update_business_card"),
    path("card-update/update-gallery/<uidb64>/", views.update_gallery, name="update_gallery"),
    path("card-update/remove-gallery-image/<uidb64>/<path:image_url>/", views.remove_gallery_image, name="remove_gallery_image"),
    path("card-update/remove-product-image/<uidb64>/<path:image_url>/", views.remove_product_image, name="remove_product_image"),
    path("card-update/update-redirect-url/<uidb64>/", views.update_redirect_url, name="update_redirect_url"),
    path("card-update/update-video-message/<uidb64>/", views.update_video_message, name="update_video_message"),
    path("card-update/update-product-viewer/<uidb64>/", views.update_product_viewer, name="update_product_viewer"),
    path("card-update/update-pdf-viewer/<uidb64>/", views.update_pdf_viewer, name="update_pdf_viewer"),
    path("card-update/update-letter/<uidb64>/", views.update_letter, name="update_letter"),
]

cards/forms.py
from core.validators import FileSizeValidator
from django import forms
from django.core.validators import FileExtensionValidator
from settings.models import PRODUCTS_CHOICES, ProductGroup

from .models import NFCCard, PurchasingCode


class URLBulkCreateForm(forms.Form):
    count = forms.IntegerField(label="Quantity", min_value=1)


class CodeBulkCreateForm(forms.ModelForm):
    count = forms.IntegerField(label="Quantity", min_value=1)
    product = forms.ChoiceField(
        label="Product", widget=forms.Select(attrs={"class": "custom-select"})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        group_choices = [
            (group.id, group.title) for group in ProductGroup.objects.all()
        ]
        static_choices = PRODUCTS_CHOICES

        self.fields["product"].choices = group_choices + static_choices

    class Meta:
        model = PurchasingCode
        fields = ["count", "duration"]
        widgets = {
            "duration": forms.Select(attrs={"class": "custom-select"}),
        }


class NFCCardForm(forms.ModelForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(), required=False, label="Old Password"
    )
    password = forms.CharField(
        widget=forms.PasswordInput(), required=True, label="Password"
    )
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput())

    class Meta:
        model = NFCCard
        fields = ["old_password", "password", "password2"]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.password:
            self.fields["old_password"].required = True
        else:
            self.fields.pop("old_password")

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get("old_password")
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if self.instance and self.instance.password and old_password:
            if not self.instance.check_password(old_password):
                raise forms.ValidationError("Old password is incorrect")

        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords do not match")

        return cleaned_data


class NFCCardTitleForm(forms.ModelForm):
    class Meta:
        model = NFCCard
        fields = ["title"]


class BusinessCardForm(forms.Form):
    title = forms.CharField(max_length=255)
    desc = forms.CharField(label="Description", max_length=255)
    logo = forms.ImageField(
        required=False, validators=[FileSizeValidator(max_size=5242880)]
    )
    show = forms.BooleanField(label="Select This Product", required=False)


class GalleryForm(forms.Form):
    images = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
        required=False,
        validators=[
            FileExtensionValidator(
                allowed_extensions=["png", "jpg", "jpeg", "gif", "webp"]
            ),
            FileSizeValidator(max_size=5242880),
        ],
    )
    show = forms.BooleanField(label="Select This Product", required=False)


class RedirectUrlForm(forms.Form):
    url = forms.URLField(required=False)
    show = forms.BooleanField(label="Select This Product", required=False)


class VideoMessageForm(forms.Form):
    video = forms.FileField(
        label="Video Message",
        required=False,
        validators=[
            FileExtensionValidator(allowed_extensions=["mp4"]),
            FileSizeValidator(max_size=52428800),
        ],
    )
    show = forms.BooleanField(label="Select This Product", required=False)


class ProductViewerForm(forms.Form):
    images = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
        required=False,
        validators=[
            FileExtensionValidator(
                allowed_extensions=["png", "jpg", "jpeg", "gif", "webp"]
            ),
            FileSizeValidator(max_size=5242880),
        ],
    )
    title = forms.CharField(max_length=255)
    desc = forms.CharField(label="Description", widget=forms.Textarea)
    show = forms.BooleanField(label="Select This Product", required=False)


class PDFViewerFom(forms.Form):
    file = forms.FileField(
        label="PDF File",
        required=False,
        validators=[
            FileExtensionValidator(allowed_extensions=["pdf"]),
            FileSizeValidator(max_size=20971520),
        ],
    )
    show = forms.BooleanField(label="Select This Product", required=False)


class LetterForm(forms.Form):
    title = forms.CharField(label="Title", max_length=255)
    text = forms.CharField(label="Your Letter", widget=forms.Textarea)
    show = forms.BooleanField(label="Select This Product", required=False)

cards/views.py
from cards.models import NFCCard
from core.utils import get_form_errors, handle_uploaded_file
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Sum
from django.db.models.functions import ExtractMonth
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from hitcount.models import HitCount
from hitcount.views import HitCountDetailView

from .forms import (BusinessCardForm, GalleryForm, LetterForm, NFCCardForm,
                    NFCCardTitleForm, PDFViewerFom, ProductViewerForm,
                    RedirectUrlForm, VideoMessageForm)
from .models import NFCCard, PurchasingCode


class NFCCardView(HitCountDetailView):
    template_name = "cards/langing_page_detail.html"
    model = NFCCard
    context_object_name = "card"
    count_hit = True

    def get_object(self, queryset=None):
        uuid = self.kwargs.get("uidb64")
        return get_object_or_404(self.model, uuid=uuid)


class NFCCardDetailView(DetailView):
    template_name = "cards/card_detail.html"
    model = NFCCard
    context_object_name = "card"

    def get_object(self, queryset=None):
        uuid = self.kwargs.get("uidb64")
        return get_object_or_404(self.model, uuid=uuid)


def link_new_card(request, uidb64):
    if request.method == "POST":
        code = request.POST.get('code')
        try:
            code = PurchasingCode.objects.get(code=code, card__isnull=True)
        except PurchasingCode.DoesNotExist:
            msg = "Wrong Code or used before"
            messages.error(request, msg)
            return redirect("cards:link_new_card", uidb64=uidb64)
        try:
            card = NFCCard.objects.get(uuid=uidb64, user__isnull=True)
        except NFCCard.DoesNotExist:
            msg = "Wrong Card uuid or used before"
            messages.error(request, msg)
            return redirect("cards:link_new_card", uidb64=uidb64)
        card.user = request.user
        data = {}
        data['choosen_product'] = {'product': ''}
        card.data = data
        card.save()
        code.card = card
        code.save()
        msg = "Card Linked Successfully"
        messages.success(request, msg)
        return redirect("cards:user_dashboard")
    return render(request, 'cards/card_register.html', {})


@login_required
def add_new_card(request):
    if request.method == "POST":
        code = request.POST.get('code')
        uuid = request.POST.get('uuid')
        try:
            code = PurchasingCode.objects.get(code=code, card__isnull=True)
        except PurchasingCode.DoesNotExist:
            msg = "Wrong Code or used before"
            messages.error(request, msg)
            return redirect("cards:add_new_card")
        try:
            card = NFCCard.objects.get(uuid=uuid, user__isnull=True)
        except NFCCard.DoesNotExist:
            msg = "Wrong Card uuid or used before"
            messages.error(request, msg)
            return redirect("cards:add_new_card")            
        card.user = request.user
        data = {}
        data['choosen_product'] = {'product': ''}
        card.data = data
        card.save()
        code.card = card
        code.save()
        msg = "Card Linked Successfully"
        messages.success(request, msg)
        return redirect("cards:user_dashboard")
    return render(request, 'cards/forms/card_add.html', {})


def check_password(request, uidb64):
    if request.method == "POST":
        card = get_object_or_404(NFCCard, uuid=uidb64)
        password = request.POST.get('password')
        if card.password == password:
            request.session['password_correct'] = True
            return redirect(card.get_absolute_url())
        else:
            request.session['password_correct'] = False
            msg = "Wrong Password, Try Again"
            messages.error(request, msg)
            return redirect(card.get_absolute_url())
    else:
        return redirect(card.get_absolute_url())


class NFCCardUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = NFCCard
    template_name = 'base/forms/create_update.html'
    success_message = "Card successfully updated"
    form_class = NFCCardForm

    def get_queryset(self):
        user = self.request.user
        qs = self.model.objects.filter(user=user)
        return qs

    def get_success_url(self):
          uidb64=self.kwargs['uidb64']
          return reverse_lazy('cards:card_detail', kwargs={'uidb64': uidb64})


class NFCCardUpdateTitle(NFCCardUpdateView):
    form_class = NFCCardTitleForm


class NFCCardListView(LoginRequiredMixin, ListView):
    model = NFCCard
    template_name = 'user/dashboard.html'

    def get_context_data(self, *args, **kwargs):
        context = super(NFCCardListView, self).get_context_data(*args, **kwargs)
        user = self.request.user
        content_types = ContentType.objects.all()
        total_hits = 0
        for content_type in content_types:
            hits = HitCount.objects.filter(
                content_type=content_type,
                object_pk__in=NFCCard.objects.filter(user=user).values_list('id', flat=True)
            ).aggregate(total_hits=Sum('hits'))['total_hits']

            if hits:
                total_hits += hits

        context['total_hits'] = total_hits
        current_year = timezone.now().year
        monthly_hits = (
            HitCount.objects.filter(
                content_type__in=content_types,
                object_pk__in=NFCCard.objects.filter(user=user).values_list('id', flat=True),
                modified__year=current_year
            ).annotate(month=ExtractMonth('modified'))
            .values('month')
            .annotate(total_hits=Sum('hits'))
            .order_by('month')
        )
        hits_by_month = {i: 0 for i in range(1, 13)}
        for entry in monthly_hits:
            hits_by_month[entry['month']] = entry['total_hits']
        context['hits_by_month'] = hits_by_month
        return context


@login_required
def update_business_card(request, uidb64):
    card = get_object_or_404(NFCCard, uuid=uidb64, user=request.user)
    if request.method == "POST":
        form = BusinessCardForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            show = form.cleaned_data.get('show')
            logo = request.FILES.get('logo')

            existing_data = card.data or {}
            existing_logo_url = existing_data.get('business_card', {}).get('logo_url', '')
            logo_url = handle_uploaded_file(request, logo) if logo else existing_logo_url
            json_data = {
                'title': title,
                'desc': desc,
                'logo_url': logo_url,
                'show': show
            }
            data = existing_data
            data['business_card'] = json_data
            if show:
                data['choosen_product'] = {'product': 'business_card'}
                if "redirect_url" in data:
                    data['redirect_url']['show'] = not show
                if "gallery" in data:
                    data['gallery']['show'] = not show
                if "letter" in data:
                    data['letter']['show'] = not show
                if "pdf_viewer" in data:
                    data['pdf_viewer']['show'] = not show
                if "video_message" in data:
                    data['video_message']['show'] = not show
            card.data = data
            card.save()
            msg = "Updated Successfully"
            messages.success(request, msg)
            return redirect("cards:card_detail", uidb64)
        else:
            msg = get_form_errors(form)
            messages.error(request, msg[0])
            return redirect("cards:card_detail", uidb64)
    else:
        if card.data:
            initial_data = card.data.get('business_card', {})
            logo_url = initial_data.get('logo_url', '')
        else:
            initial_data = {}
            logo_url = None
        form = BusinessCardForm(initial=initial_data)
    
    return render(request, 'cards/forms/business_card.html', {'form': form, 'logo_url': logo_url, "active": "dashboard"})


@login_required
def update_gallery(request, uidb64):
    card = get_object_or_404(NFCCard, uuid=uidb64, user=request.user)
    
    if request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES)
        gallery_data = None
        if form.is_valid():
            files = request.FILES.getlist('images')
            show = form.cleaned_data.get('show')
            existing_data = card.data or {}
            existing_images = existing_data.get('gallery', {}).get('images', [])
            image_urls = existing_images or []
            for file in files:
                file_url = handle_uploaded_file(request, file)
                image_urls.append(file_url)
            
            data = card.data or {}
            data['gallery'] = {'images': image_urls, 'show': show}
            if show:
                data['choosen_product'] = {'product': 'gallery'}
                if "business_card" in data:
                    data['business_card']['show'] = not show
                if "redirect_url" in data:
                    data['redirect_url']['show'] = not show
                if "letter" in data:
                    data['letter']['show'] = not show
                if "pdf_viewer" in data:
                    data['pdf_viewer']['show'] = not show
                if "video_message" in data:
                    data['video_message']['show'] = not show
            card.data = data

templates/cards/forms/business_card.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Update Business Card
{% endblock %}


{% block content %}

<div class="container my-5 pt-5">
    <h2 class="mainTopic">Update Business Card {{ object }}</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}<br>
                {% if logo_url %}
                <p>Current image:</p>
                <img src="{{ logo_url }}" alt="Current Image" style="max-width: 300px; max-height: 300px;"><br>
                {% endif %}
                <br>
                <button class="btn main-btn" type="submit">Save</button>
                <a class="btn main-btn" id="back-page">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/cards/forms/card_add.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
Register Your Card
{% endblock %}
{% block content %}


<div class="d-flex flex-row align-items-center">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2 class="mainTopic">Add new card</h2>
                <div class="mt-4 card">
                    <div class="card-body">
                        <form method="post" class="py-3">
                            {% csrf_token %}
                            <input type="text" name="uuid" class="form-control  mb-4" placeholder="Card UUID">
                            <input type="text" name="code" class="form-control mb-4" placeholder="Your Purchasing Code">
                            <input type="submit" name="submit" value="Add" class="btn main-btn">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/cards/forms/gallery.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Update Gallery
{% endblock %}


{% block content %}

<div class="container my-5 pt-5">
    <h2 class="mainTopic">Update Gallery</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4" enctype="multipart/form-data" id="gallery-form">
                {% csrf_token %}
                <div class="image-container" id="image-container">
                    {% for image in gallery_data %}
                    <div class="image-item">
                        <img src="{{ image }}" alt="Image">
                        <a href="{% url 'cards:remove_gallery_image' uidb64=uuid image_url=image %}" class="remove-button btn btn-sm danger-btn">X</a>

                    </div>
                    {% endfor %}
                </div>
                {{ form|crispy }}
                <button class="btn main-btn" type="submit">Save</button>
                <a class="btn main-btn" id="back-page">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/cards/forms/letter.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Update Letter
{% endblock %}


{% block content %}

<div class="container my-5 pt-5">
    <h2 class="mainTopic">Update Letter</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button class="btn main-btn" type="submit">Save</button>
                <a class="btn main-btn" id="back-page">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/cards/forms/pdf_viewer.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Update PDF Viewer
{% endblock %}


{% block content %}

<div class="container my-5 pt-5">
    <h2 class="mainTopic">Update PDF Viewer</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}<br>
                {% if file_name %}
                <p>Current file: {{ file_name }}</p>
                {% endif %}
                <button class="btn main-btn" type="submit">Save</button>
                <a class="btn main-btn" id="back-page">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/cards/forms/product_viewer.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Update Product Viewer
{% endblock %}


{% block content %}

<div class="container my-5 pt-5">
    <h2 class="mainTopic">Update Product Viewer</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="image-container" id="image-container">
                    {% for image in product_images %}
                    <div class="image-item">
                        <img src="{{ image }}" alt="Image">
                        <a href="{% url 'cards:remove_product_image' uidb64=uuid image_url=image %}" class="remove-button btn btn-sm danger-btn">X</a>
                    </div>
                    {% endfor %}
                </div>
                {{ form|crispy }}<br>
                <button class="btn main-btn" type="submit">Save</button>
                <a class="btn main-btn" id="back-page">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/cards/forms/redirect_url.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Update Redirect URL
{% endblock %}


{% block content %}

<div class="container my-5 pt-5">
    <h2 class="mainTopic">Update Redirect URL</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4">
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button class="btn main-btn" type="submit">Save</button>
                <a class="btn main-btn" id="back-page">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/cards/forms/video_message.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Update Video Message
{% endblock %}


{% block content %}

<div class="container my-5 pt-5">
    <h2 class="mainTopic">Update Video Message</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}<br>
                {% if video_name %}
                <p>Current Video: {{ video_name }}</p>
                {% endif %}
                <button class="btn main-btn" type="submit">Save</button>
                <a class="btn main-btn" id="back-page">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}