NFC_Project/urls.py
from core.views import handler500, custom_admin_index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _


admin.site.index_title = "Website Managment"
admin.site.site_header = "Chipper Group"

urlpatterns = [
    path('admin/', custom_admin_index, name='custom_admin_index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('users.passwords.urls')),
    path('', include('cards.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = handler500

cards/urls.py
from django.urls import path

from . import views

app_name = "cards"


urlpatterns = [
    path(
        "",
        views.NFCCardListView.as_view(extra_context={"active": "dashboard"}),
        name="user_dashboard",
    ),
    path(
        "landingPage/<uidb64>/",
        views.NFCCardView.as_view(),
        name="landing_page",
    ),
    path(
        "card-update/<uidb64>/",
        views.NFCCardDetailView.as_view(extra_context={"active": "dashboard"}),
        name="card_detail",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-password/",
        views.NFCCardUpdateView.as_view(extra_context={"active": "dashboard"}),
        name="update_card_password",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-title/",
        views.NFCCardUpdateTitle.as_view(extra_context={"active": "dashboard"}),
        name="update_card_title",
    ),
    path("cards-link/<uidb64>/", views.link_new_card, name="link_new_card"),
    path("cards-add/", views.add_new_card, name="add_new_card"),
    path("check-password/<uidb64>/", views.check_password, name="check_password"),
    path("card-update/update-business-card/<uidb64>/", views.update_business_card, name="update_business_card"),
    path("card-update/update-gallery/<uidb64>/", views.update_gallery, name="update_gallery"),
    path("card-update/remove-gallery-image/<uidb64>/<path:image_url>/", views.remove_gallery_image, name="remove_gallery_image"),
    path("card-update/remove-product-image/<uidb64>/<path:image_url>/", views.remove_product_image, name="remove_product_image"),
    path("card-update/update-redirect-url/<uidb64>/", views.update_redirect_url, name="update_redirect_url"),
    path("card-update/update-video-message/<uidb64>/", views.update_video_message, name="update_video_message"),
    path("card-update/update-product-viewer/<uidb64>/", views.update_product_viewer, name="update_product_viewer"),
    path("card-update/update-pdf-viewer/<uidb64>/", views.update_pdf_viewer, name="update_pdf_viewer"),
    path("card-update/update-letter/<uidb64>/", views.update_letter, name="update_letter"),
]

users/urls.py
from django.urls import path

from . import views
from .forms import CustomLoginForm

app_name = "users"


urlpatterns = [
    path(
        "profile/",
        views.UserHomeView.as_view(extra_context={"active": "profile"}),
        name="user_profile",
    ),
    path(
        "details/",
        views.UserUpdateView.as_view(extra_context={"active": "profile"}),
        name="account_update",
    ),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path(
        "login/",
        views.CustomLoginView.as_view(extra_context={"active": "login"}),
        name="login",
    ),
    path("register/", views.RegisterView.as_view(extra_context={"active": "register"}), name="register"),
]

templates/base/css.html
{% load static %}
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
    integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"
    integrity="sha512-t4GWSVZO1eC8BM339Xd7Uphw5s17a86tIZIj8qRxhnKub6WoyhnrxeCIMeAqBPgdZGlCcG2PrZjMc+Wr78+5Xg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- Custom styles -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">

templates/base/dashboard.html
<div class="d-flex flex-row align-items-center">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <h1>Dashboard</h1>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 mt-3 text-center">
                <div class="card bg-dark bg-gradient text-white">
                    <p class="card-title mt-3">Cards</p>
                    <div class="card-body">
                    <p class="font-weight-bold">1405</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 mt-3 text-center">
                <a class="link-style" href="">
                  <div class="card bg-primary bg-gradient text-white">
                        <p class="card-title mt-3 text-white">Users</p>
                        <div class="card-body">
                            <p class="font-weight-bold">578</p>
                        </div>
                  </div>
                </a>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 mt-3 text-center">
                <a class="link-style" href="">
                    <div class="card bg-success bg-gradient text-white">
                        <p class="card-title mt-3">Sales</p>
                        <div class="card-body">
                            <p class="font-weight-bold">65421 EGP</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

templates/base/footer.html
{% load static %}

<footer class="text-center">
    <div class="container">
        <div class="row mt-4">
            <hr>
            <p>&copy; CopyRight 2024 {% if current_year %} - {{ current_year }}{% endif %} 
             All Rights Reserved.
             Powerd By <a class="link-style" href="/">Chipper Group</a>.
            </p>
            <hr>
        </div>
    </div>
</footer>

templates/base/js.html
{% load static %}
<!-- Bootstrap JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"
	integrity="sha512-VK2zcvntEufaimc+efOYi622VN5ZacdnufnmX7zIhCPmjhKnOi9ZDMtg1/ug5l183f19gG1/cBstPO4D8N/Img=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Sweet alerts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.7.11/sweetalert2.all.min.js"
	integrity="sha512-sZf2OK8od53udtGBBdzSqg3BGjjL3BpM5K4dQgB0mmhumO07aWOLmBK917w5cbdLWPfILjJzKgJcYm+neEBUDw=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
	integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Custom scripts -->
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

templates/base/messages.html
{% load i18n %}
{% if messages %}
    {% if messages|length > 1 %}
        <script>
            Swal.fire({
                {% for message in messages %}
                icon: "{{ message.tags }}",
                title: '{% if message.tags == "error" %}{% trans "Error!" %}{% elif message.tags == "success" %}{% trans "Success" %}{% elif message.tags == "warning" %}{% trans "Warning" %}{% else %}{% trans "Info" %}{% endif %}',
                {% endfor %}
                html: "<ul class='errorlist'>{% for message in messages %}<li {% if message.tags == 'success'%}class='successlist'{% endif %}>{{ message }}</li>{% endfor %}</ul>",
                confirmButtonText: '{% trans "OK" %}',
                confirmButtonColor: '#269ffd',

            });
        </script>
    {% else %}
        {% for message in messages %}
        <script>
            Swal.fire({
                icon: "{{ message.tags }}",
                title: '{% if message.tags == "error" %}{% trans "Error!" %}{% elif message.tags == "success" %}{% trans "Success" %}{% elif message.tags == "warning" %}{% trans "Warning" %}{% else %}{% trans "Info" %}{% endif %}',
                html: "<h4>{{ message }}</h4>",
                confirmButtonText: '{% trans "OK" %}',
                confirmButtonColor: '#269ffd',

            });
        </script>
        {% endfor %}
    {% endif %}
{% endif %}

templates/base/navbar.html
{% load static %}
{% comment %}
<nav class="navbar navbar-expand-lg navbar navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse w-100" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if active == 'home' %}active{% endif %}" aria-current="page" href="/">Home</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto w-100 justify-content-end">
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if active == 'login' %}active{% endif %}" href="{% url 'users:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if active == 'register' %}active{% endif %}" href="{% url 'users:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% endcomment %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid  text-center">
        {% if user.is_authenticated %}
        <button type="button" id="sidebarCollapse" class="btn dark-btn me-3">
            <i class="fas fa-align-left"></i>
        </button>
        {% endif %}
        <button class="btn dark-btn d-inline-block d-lg-none ml-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if not user.is_authenticated %}
            <ul class="nav navbar-nav ml-end">
                <li class="nav-item {% if active == 'login' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'users:login' %}">login</a>
                </li>
                <li class="nav-item {% if active == 'register' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>

templates/base/pagination.html
{% if objects.has_other_pages %}
<div class="col-12 pagi">
    <nav>
        <ul class="pagination">
            {% if objects.has_previous %}
            <li class="page-item">
                <a class="page-link prev" href="?page={{ objects.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true"><</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" aria-label="Previous">
                    <span aria-hidden="true"><</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% endif %}
            {% for i in objects.paginator.page_range %}
            {% if objects.number > 2 and forloop.first %}
            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            <li class="page-item disabled"><a class="page-link me-2" href="&page=1">...</a></li>
            {% endif %}
            {% if objects.number == i %}
            <li class="page-item"><a class="page-link pagination-active" href="#">{{ i }}</a></li>
            {% elif i > objects.number|add:'-2' and i < objects.number|add:'2' %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% if objects.paginator.num_pages > objects.number|add:'1' and forloop.last %}
            <li class="page-item disabled"><a class="page-link">...</a></li>
            <li class="page-item">
                <a class="page-link me-2"
                    href="?page={{ objects.paginator.num_pages }}">{{ objects.paginator.num_pages }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if objects.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ objects.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" aria-label="Next">
                    <span aria-hidden="true">></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

templates/base/sidebar.html
{% load static %}
<!-- Sidebar  -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>Chipper Group</h3>
    </div>

    <ul class="list-unstyled components">
        <h3>
            <img src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'img/user.jpg' %}{% endif %}" alt="{{ user.username }}" height="140" width="160" style="border-radius: 50%;">
            <p>{{ user }}</p>
        </h3>
        {% comment %}
        <li class="side-li">
            <a href="#homeSubmenu" data-bs-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="#">Home 1</a>
                </li>
                <li>
                    <a href="#">Home 2</a>
                </li>
                <li>
                    <a href="#">Home 3</a>
                </li>
            </ul>
        </li>
        {% endcomment %}
        <li class="side-li {% if active == 'dashboard' %}active{% endif %}">
            <a href="{% url 'cards:user_dashboard' %}">
                <i class="fa-solid fa-gauge-high"></i> 
                <span style="margin-left:10px;">Dashboard
                    {% if active == "dashboard" %}
                    <i class="fas fa-angle-double-right"></i>
                    {% endif %}
                </span>
            </a>
        </li>
        <li class="side-li {% if active == 'profile' %}active{% endif %}">
            <a href="{% url 'users:user_profile' %}"><i class="fas fa-address-card"></i> 
                <span style="margin-left:10px;">Profile
                    {% if active == "profile" %}
                    <i class="fas fa-angle-double-right"></i>
                    {% endif %}
                </span>
            </a>
        </li>
        <li class="side-li">
            <a href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> <span style="margin-left:10px;">Log out</span></a>
        </li>
        {% if user.is_superuser or user.is_staff %}
        <li class="side-li">
            <a href="{% url 'admin:index' %}"><i class="fas fa-external-link-alt"></i> <span style="margin-left:10px;">Manage site</span></a>
        </li>
        {% endif %}
    </ul>
    <div class="div-border"></div>
    <ul class="list-unstyled buttons">
        <li>
            <a href="{% url 'cards:add_new_card' %}" class="btn primary-btn">Add New Card</a>
        </li>
    </ul>
</nav>

templates/base/user_bar.html
<div class="col-12 col-md-12 col-lg-2 mt-5 pt-1">
    <div class="card">
        <div class="nav flex-column">
            <p class="text-center  mt-2">
                <span class="border border-primary rounded-pill rounded-lg">
                    <span class="me-2 ms-2">
                        {% if request.user.first_name %}
                        {{ request.user.first_name }}
                        {% else %}
                        {{ request.user.username }}
                        {% endif %}
                    </span>
                </span>
                <br>
                <span>Cards: {{ user.user_cards.count }}</span>
            </p>
            <a class="btn primary-btn btn-sm mb-1 {% if active == 'profile' %}active{% endif %}" href="{% url 'users:user_profile' %}"><i class="fas fa-address-card"></i> Profile
                {% if active == "profile" %}
                <i class="fas fa-angle-double-right"></i>
                {% endif %}
            </a>
            <a class="btn primary-btn btn-sm mb-1 {% if active == 'dashboard' %}active{% endif %}" href="{% url 'cards:user_dashboard' %}"><i class="fa-solid fa-gauge-high"></i> Dashboard
                {% if active == "dashboard" %}
                <i class="fas fa-angle-double-right"></i>
                {% endif %}
            </a>
            <a class="btn primary-btn btn-sm mb-1" href="{% url 'users:logout' %}">
                <i class="fas fa-sign-out-alt"></i> Log out
            </a>
            {% if user.is_superuser or user.is_staff %}
            <a class="btn primary-btn btn-sm mb-1" href="{% url 'admin:index' %}"> 
                <i class="fas fa-external-link-alt"></i> Manage site
            </a>
            {% endif %}
        </div>
    </div>
</div>