NFC_Project/urls.py
from core.views import handler500, custom_admin_index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _


admin.site.index_title = "Website Managment"
admin.site.site_header = "Chipper Group"

urlpatterns = [
    path('admin/', custom_admin_index, name='custom_admin_index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('users.passwords.urls')),
    path('', include('cards.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = handler500

cards/urls.py
from django.urls import path

from . import views

app_name = "cards"


urlpatterns = [
    path(
        "",
        views.NFCCardListView.as_view(extra_context={"active": "dashboard"}),
        name="user_dashboard",
    ),
    path(
        "landingPage/<uidb64>/",
        views.NFCCardView.as_view(),
        name="landing_page",
    ),
    path(
        "card-update/<uidb64>/",
        views.NFCCardDetailView.as_view(extra_context={"active": "dashboard"}),
        name="card_detail",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-password/",
        views.NFCCardUpdateView.as_view(extra_context={"active": "dashboard"}),
        name="update_card_password",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-title/",
        views.NFCCardUpdateTitle.as_view(extra_context={"active": "dashboard"}),
        name="update_card_title",
    ),
    path("cards-link/<uidb64>/", views.link_new_card, name="link_new_card"),
    path("cards-add/", views.add_new_card, name="add_new_card"),
    path("check-password/<uidb64>/", views.check_password, name="check_password"),
    path("card-update/update-business-card/<uidb64>/", views.update_business_card, name="update_business_card"),
    path("card-update/update-gallery/<uidb64>/", views.update_gallery, name="update_gallery"),
    path("card-update/remove-gallery-image/<uidb64>/<path:image_url>/", views.remove_gallery_image, name="remove_gallery_image"),
    path("card-update/remove-product-image/<uidb64>/<path:image_url>/", views.remove_product_image, name="remove_product_image"),
    path("card-update/update-redirect-url/<uidb64>/", views.update_redirect_url, name="update_redirect_url"),
    path("card-update/update-video-message/<uidb64>/", views.update_video_message, name="update_video_message"),
    path("card-update/update-product-viewer/<uidb64>/", views.update_product_viewer, name="update_product_viewer"),
    path("card-update/update-pdf-viewer/<uidb64>/", views.update_pdf_viewer, name="update_pdf_viewer"),
    path("card-update/update-letter/<uidb64>/", views.update_letter, name="update_letter"),
]

users/urls.py
from django.urls import path

from . import views
from .forms import CustomLoginForm

app_name = "users"


urlpatterns = [
    path(
        "profile/",
        views.UserHomeView.as_view(extra_context={"active": "profile"}),
        name="user_profile",
    ),
    path(
        "details/",
        views.UserUpdateView.as_view(extra_context={"active": "profile"}),
        name="account_update",
    ),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path(
        "login/",
        views.CustomLoginView.as_view(extra_context={"active": "login"}),
        name="login",
    ),
    path("register/", views.RegisterView.as_view(extra_context={"active": "register"}), name="register"),
]

cards/views.py
from cards.models import NFCCard
from core.utils import get_form_errors, handle_uploaded_file
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Sum
from django.db.models.functions import ExtractMonth
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from hitcount.models import HitCount
from hitcount.views import HitCountDetailView

from .forms import (BusinessCardForm, GalleryForm, LetterForm, NFCCardForm,
                    NFCCardTitleForm, PDFViewerFom, ProductViewerForm,
                    RedirectUrlForm, VideoMessageForm)
from .models import NFCCard, PurchasingCode


class NFCCardView(HitCountDetailView):
    template_name = "cards/langing_page_detail.html"
    model = NFCCard
    context_object_name = "card"
    count_hit = True

    def get_object(self, queryset=None):
        uuid = self.kwargs.get("uidb64")
        return get_object_or_404(self.model, uuid=uuid)


class NFCCardDetailView(DetailView):
    template_name = "cards/card_detail.html"
    model = NFCCard
    context_object_name = "card"

    def get_object(self, queryset=None):
        uuid = self.kwargs.get("uidb64")
        return get_object_or_404(self.model, uuid=uuid)


def link_new_card(request, uidb64):
    if request.method == "POST":
        code = request.POST.get('code')
        try:
            code = PurchasingCode.objects.get(code=code, card__isnull=True)
        except PurchasingCode.DoesNotExist:
            msg = "Wrong Code or used before"
            messages.error(request, msg)
            return redirect("cards:link_new_card", uidb64=uidb64)
        try:
            card = NFCCard.objects.get(uuid=uidb64, user__isnull=True)
        except NFCCard.DoesNotExist:
            msg = "Wrong Card uuid or used before"
            messages.error(request, msg)
            return redirect("cards:link_new_card", uidb64=uidb64)
        card.user = request.user
        data = {}
        data['choosen_product'] = {'product': ''}
        card.data = data
        card.save()
        code.card = card
        code.save()
        msg = "Card Linked Successfully"
        messages.success(request, msg)
        return redirect("cards:user_dashboard")
    return render(request, 'cards/card_register.html', {})


@login_required
def add_new_card(request):
    if request.method == "POST":
        code = request.POST.get('code')
        uuid = request.POST.get('uuid')
        try:
            code = PurchasingCode.objects.get(code=code, card__isnull=True)
        except PurchasingCode.DoesNotExist:
            msg = "Wrong Code or used before"
            messages.error(request, msg)
            return redirect("cards:add_new_card")
        try:
            card = NFCCard.objects.get(uuid=uuid, user__isnull=True)
        except NFCCard.DoesNotExist:
            msg = "Wrong Card uuid or used before"
            messages.error(request, msg)
            return redirect("cards:add_new_card")            
        card.user = request.user
        data = {}
        data['choosen_product'] = {'product': ''}
        card.data = data
        card.save()
        code.card = card
        code.save()
        msg = "Card Linked Successfully"
        messages.success(request, msg)
        return redirect("cards:user_dashboard")
    return render(request, 'cards/forms/card_add.html', {})


def check_password(request, uidb64):
    if request.method == "POST":
        card = get_object_or_404(NFCCard, uuid=uidb64)
        password = request.POST.get('password')
        if card.password == password:
            request.session['password_correct'] = True
            return redirect(card.get_absolute_url())
        else:
            request.session['password_correct'] = False
            msg = "Wrong Password, Try Again"
            messages.error(request, msg)
            return redirect(card.get_absolute_url())
    else:
        return redirect(card.get_absolute_url())


class NFCCardUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = NFCCard
    template_name = 'base/forms/create_update.html'
    success_message = "Card successfully updated"
    form_class = NFCCardForm

    def get_queryset(self):
        user = self.request.user
        qs = self.model.objects.filter(user=user)
        return qs

    def get_success_url(self):
          uidb64=self.kwargs['uidb64']
          return reverse_lazy('cards:card_detail', kwargs={'uidb64': uidb64})


class NFCCardUpdateTitle(NFCCardUpdateView):
    form_class = NFCCardTitleForm


class NFCCardListView(LoginRequiredMixin, ListView):
    model = NFCCard
    template_name = 'user/dashboard.html'

    def get_context_data(self, *args, **kwargs):
        context = super(NFCCardListView, self).get_context_data(*args, **kwargs)
        user = self.request.user
        content_types = ContentType.objects.all()
        total_hits = 0
        for content_type in content_types:
            hits = HitCount.objects.filter(
                content_type=content_type,
                object_pk__in=NFCCard.objects.filter(user=user).values_list('id', flat=True)
            ).aggregate(total_hits=Sum('hits'))['total_hits']

            if hits:
                total_hits += hits

        context['total_hits'] = total_hits
        current_year = timezone.now().year
        monthly_hits = (
            HitCount.objects.filter(
                content_type__in=content_types,
                object_pk__in=NFCCard.objects.filter(user=user).values_list('id', flat=True),
                modified__year=current_year
            ).annotate(month=ExtractMonth('modified'))
            .values('month')
            .annotate(total_hits=Sum('hits'))
            .order_by('month')
        )
        hits_by_month = {i: 0 for i in range(1, 13)}
        for entry in monthly_hits:
            hits_by_month[entry['month']] = entry['total_hits']
        context['hits_by_month'] = hits_by_month
        return context


@login_required
def update_business_card(request, uidb64):
    card = get_object_or_404(NFCCard, uuid=uidb64, user=request.user)
    if request.method == "POST":
        form = BusinessCardForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            show = form.cleaned_data.get('show')
            logo = request.FILES.get('logo')

            existing_data = card.data or {}
            existing_logo_url = existing_data.get('business_card', {}).get('logo_url', '')
            logo_url = handle_uploaded_file(request, logo) if logo else existing_logo_url
            json_data = {
                'title': title,
                'desc': desc,
                'logo_url': logo_url,
                'show': show
            }
            data = existing_data
            data['business_card'] = json_data
            if show:
                data['choosen_product'] = {'product': 'business_card'}
                if "redirect_url" in data:
                    data['redirect_url']['show'] = not show
                if "gallery" in data:
                    data['gallery']['show'] = not show
                if "letter" in data:
                    data['letter']['show'] = not show
                if "pdf_viewer" in data:
                    data['pdf_viewer']['show'] = not show
                if "video_message" in data:
                    data['video_message']['show'] = not show
            card.data = data
            card.save()
            msg = "Updated Successfully"
            messages.success(request, msg)
            return redirect("cards:card_detail", uidb64)
        else:
            msg = get_form_errors(form)
            messages.error(request, msg[0])
            return redirect("cards:card_detail", uidb64)
    else:
        if card.data:
            initial_data = card.data.get('business_card', {})
            logo_url = initial_data.get('logo_url', '')
        else:
            initial_data = {}
            logo_url = None
        form = BusinessCardForm(initial=initial_data)
    
    return render(request, 'cards/forms/business_card.html', {'form': form, 'logo_url': logo_url, "active": "dashboard"})


@login_required
def update_gallery(request, uidb64):
    card = get_object_or_404(NFCCard, uuid=uidb64, user=request.user)
    
    if request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES)
        gallery_data = None
        if form.is_valid():
            files = request.FILES.getlist('images')
            show = form.cleaned_data.get('show')
            existing_data = card.data or {}
            existing_images = existing_data.get('gallery', {}).get('images', [])
            image_urls = existing_images or []
            for file in files:
                file_url = handle_uploaded_file(request, file)
                image_urls.append(file_url)
            
            data = card.data or {}
            data['gallery'] = {'images': image_urls, 'show': show}
            if show:
                data['choosen_product'] = {'product': 'gallery'}
                if "business_card" in data:
                    data['business_card']['show'] = not show
                if "redirect_url" in data:
                    data['redirect_url']['show'] = not show
                if "letter" in data:
                    data['letter']['show'] = not show
                if "pdf_viewer" in data:
                    data['pdf_viewer']['show'] = not show
                if "video_message" in data:
                    data['video_message']['show'] = not show
            card.data = data

templates/cards/card_detail.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load i18n %}
{% load custom_filters %}
{% block title %}
    {% trans 'Dashboard' %}
{% endblock %}
{% block content %}
<!-- Page Content  -->
<div class="contaner">
    <div>
        <h3 class="text-center">Update Card</h3>
        <div class="row">
            {% get_hit_count for card as hits %}
            <div class="card col-md-12 mt-3 py-5 shadow-lg p-5 m3-3 bg-white rounded">
                <div class="card-header">
                    <h4>{{ card }} <a href="{{ card.get_absolute_url }}" class="btn main-btn" target="_blank">View on Site</a></h4>
                </div>
                <div class="card-body">
                    <a href="{% url 'cards:update_card_password' card.uuid card.pk %}" class="btn main-btn mb-1"> 
                        {% if card.password %}Update Password {% else %}Set Password{% endif %}
                    </a>
                    <a href="{% url 'cards:update_card_title' card.uuid card.pk %}" class="btn main-btn mb-1"> 
                        {% if card.title %}Update Title {% else %}Set Title{% endif %}
                    </a>
                    <a href="{% url 'cards:update_business_card' card.uuid %}" class="btn main-btn mb-1"> 
                    Update Business Card
                    </a>
                    <a href="{% url 'cards:update_gallery' card.uuid %}" class="btn main-btn mb-1"> 
                    Update Gallery
                    </a>
                    <br>
                    <a href="{% url 'cards:update_redirect_url' card.uuid %}" class="btn main-btn mb-1"> 
                    Update Redirect URL
                    </a>
                    <a href="{% url 'cards:update_video_message' card.uuid %}" class="btn main-btn mb-1"> 
                    Update Video Message
                    </a>
                    <a href="{% url 'cards:update_product_viewer' card.uuid %}" class="btn main-btn mb-1"> 
                    Update Product Viewer
                    </a>
                    <br>
                    <a href="{% url 'cards:update_pdf_viewer' card.uuid %}" class="btn main-btn mb-1"> 
                    Update PDF Viewer
                    </a>
                    <a href="{% url 'cards:update_letter' card.uuid %}" class="btn main-btn mb-1"> 
                    Update Letter
                    </a>
                    <p>Password: {% if card.password %}{{ card.password|mask_password }}{% else %}<span class="text-danger">{% trans 'not specified' %}</span>{% endif %}</p>
                    <p>
                        Views: <small class="ms-3"><i class="fa-regular fa-eye"></i> {{ hits }}</small>
                    </p>
                    <a href="{% url 'cards:user_dashboard' %}" class="btn btn-sm main-btn">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block extrajs %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="text/javascript" src="{% static 'js/dashboard.js' %}"></script>
{% endblock %}

templates/cards/card_register.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
Register Your Card
{% endblock %}
{% block content %}


<div class="d-flex flex-row align-items-center">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <h2 class="mainTopic">Register new card</h2>
                <div class="mt-4">
                    <form method="post">
                        {% csrf_token %}
                        <input type="text" name="code" class="form-control custom-input" placeholder="Your Purchasing Code">
                        <input type="submit" name="submit" value="Link Now" class="btn main-btn">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/cards/langing_page_detail.html
{% extends 'landing_base.html' %}
{% load static %}
{% load i18n %}
{% load hitcount_tags %}
{% block title %}
    {% trans 'Home' %}
{% endblock %}
{% block content %}



<div class="d-flex flex-row align-items-center">
    <div class="container mt-5">
        <div class="row justify-content-center">
            {% if card.user %}
                {% if card.password %}
                    {% if request.session.password_correct or request.user == card.user %}
                    <div class="col-md-12 text-center">
                        {% if card.data.choosen_product.product == "business_card" %}
                        {% include 'cards/base/business_card.html' %}
                        {% elif card.data.choosen_product.product == "gallery" %}
                        {% include 'cards/base/gallery.html' %}
                        {% elif card.data.choosen_product.product == "redirect_url" %}
                        {% include 'cards/base/redirect_url.html' %}
                        {% elif card.data.choosen_product.product == "letter" %}
                        {% include 'cards/base/letter.html' %}
                        {% elif card.data.choosen_product.product == "video_message" %}
                        {% include 'cards/base/video_message.html' %}
                        {% elif card.data.choosen_product.product == "pdf_viewer" %}
                        {% include 'cards/base/pdf_viewer.html' %}
                        {% elif card.data.choosen_product.product == "product_viewer" %}
                        {% include 'cards/base/product_viewer.html' %}
                        {% else %}
                        <p class="text-danger">No data in this page.</p>
                        {% endif %}
                    </div>
                    {% else %}
                    <div class="col-md-12 text-center">
                        <h2>This card is password protected</h2>
                        <div class="mt-4">
                            <form method="POST" action="{% url 'cards:check_password' card.uuid %}">
                                {% csrf_token %}
                                <input type="password" name="password" class="form-control custom-input" placeholder="Password">
                                <input type="submit" name="submit" value="Submit" class="btn main-btn">
                            </form>
                        </div>
                    </div>
                    {% endif %}
                {% else %}
                <div class="col-md-12 text-center">
                    {% if card.data.choosen_product.product == "business_card" %}
                    {% include 'cards/base/business_card.html' %}
                    {% elif card.data.choosen_product.product == "gallery" %}
                    {% include 'cards/base/gallery.html' %}
                    {% elif card.data.choosen_product.product == "redirect_url" %}
                    {% include 'cards/base/redirect_url.html' %}
                    {% elif card.data.choosen_product.product == "letter" %}
                    {% include 'cards/base/letter.html' %}
                    {% elif card.data.choosen_product.product == "video_message" %}
                    {% include 'cards/base/video_message.html' %}
                    {% elif card.data.choosen_product.product == "pdf_viewer" %}
                    {% include 'cards/base/pdf_viewer.html' %}
                    {% elif card.data.choosen_product.product == "product_viewer" %}
                    {% include 'cards/base/product_viewer.html' %}
                    {% else %}
                    <p class="text-danger">No data in this page.</p>
                    {% endif %}
                </div>
                {% endif %}
            {% else %}
            <div class="col-md-12 text-center">
                <div class="col-md-12 text-center">
                    <h5 class="display-1">Register Your Card</h5>
                    {% if user.is_authenticated %}
                    <h3>You are logged in</h3>
                    <h3><a href="{% url 'cards:link_new_card' card.uuid %}" class="link-style">Link with your logged in account ?</a> | <a href="{% url 'users:logout' %}?uuid={{card.uuid}}" class="link-style">Log Me Out First</a></h3>
                    {% else %}
                    <h3>
                        <a href="{% url 'users:register' %}?uuid={{ card.uuid}}" class="link-style">Create New Account</a> | <a href="{% url 'users:login' %}?uuid={{card.uuid}}" class="link-style">Add to Existing Account</a>
                    </h3>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-12 text-center">
                
            </div>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}


{% block extrajs %}

<script>
document.addEventListener('DOMContentLoaded', function() {
    var countdownElement = document.getElementById('countdown');
    var redirectLink = document.getElementById('redirect-link');
    var countdown = 10; // seconds

    var interval = setInterval(function() {
        countdown--;
        countdownElement.textContent = countdown;
        if (countdown <= 0) {
            clearInterval(interval);
            window.location.href = redirectLink.href;
        }
    }, 1000);
});
</script>
{% endblock %}