NFC_Project/urls.py
from core.views import handler500, custom_admin_index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _


admin.site.index_title = "Website Managment"
admin.site.site_header = "Chipper Group"

urlpatterns = [
    path('admin/', custom_admin_index, name='custom_admin_index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('users.passwords.urls')),
    path('', include('cards.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = handler500

cards/urls.py
from django.urls import path

from . import views

app_name = "cards"


urlpatterns = [
    path(
        "",
        views.NFCCardListView.as_view(extra_context={"active": "dashboard"}),
        name="user_dashboard",
    ),
    path(
        "landingPage/<uidb64>/",
        views.NFCCardView.as_view(),
        name="landing_page",
    ),
    path(
        "card-update/<uidb64>/",
        views.NFCCardDetailView.as_view(extra_context={"active": "dashboard"}),
        name="card_detail",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-password/",
        views.NFCCardUpdateView.as_view(extra_context={"active": "dashboard"}),
        name="update_card_password",
    ),
    path(
        "card-update/<uidb64>/<int:pk>/update-title/",
        views.NFCCardUpdateTitle.as_view(extra_context={"active": "dashboard"}),
        name="update_card_title",
    ),
    path("cards-link/<uidb64>/", views.link_new_card, name="link_new_card"),
    path("cards-add/", views.add_new_card, name="add_new_card"),
    path("check-password/<uidb64>/", views.check_password, name="check_password"),
    path("card-update/update-business-card/<uidb64>/", views.update_business_card, name="update_business_card"),
    path("card-update/update-gallery/<uidb64>/", views.update_gallery, name="update_gallery"),
    path("card-update/remove-gallery-image/<uidb64>/<path:image_url>/", views.remove_gallery_image, name="remove_gallery_image"),
    path("card-update/remove-product-image/<uidb64>/<path:image_url>/", views.remove_product_image, name="remove_product_image"),
    path("card-update/update-redirect-url/<uidb64>/", views.update_redirect_url, name="update_redirect_url"),
    path("card-update/update-video-message/<uidb64>/", views.update_video_message, name="update_video_message"),
    path("card-update/update-product-viewer/<uidb64>/", views.update_product_viewer, name="update_product_viewer"),
    path("card-update/update-pdf-viewer/<uidb64>/", views.update_pdf_viewer, name="update_pdf_viewer"),
    path("card-update/update-letter/<uidb64>/", views.update_letter, name="update_letter"),
]

users/passwords/urls.py
from django.contrib.auth import views
from django.urls import path

urlpatterns = [
    path(
        "password_change/",
        views.PasswordChangeView.as_view(extra_context={"active": "profile"}),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(extra_context={"active": "profile"}),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(extra_context={"active": "profile"}),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(extra_context={"active": "profile"}),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(extra_context={"active": "profile"}),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(extra_context={"active": "profile"}),
        name="password_reset_complete",
    ),
]

users/urls.py
from django.urls import path

from . import views
from .forms import CustomLoginForm

app_name = "users"


urlpatterns = [
    path(
        "profile/",
        views.UserHomeView.as_view(extra_context={"active": "profile"}),
        name="user_profile",
    ),
    path(
        "details/",
        views.UserUpdateView.as_view(extra_context={"active": "profile"}),
        name="account_update",
    ),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path(
        "login/",
        views.CustomLoginView.as_view(extra_context={"active": "login"}),
        name="login",
    ),
    path("register/", views.RegisterView.as_view(extra_context={"active": "register"}), name="register"),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from PIL import Image

ROLE_CHOICES = [
    ("customer", "Customer"),
    ("superuser", "Super User"),
    ("url", "URL Maker"),
    ("artist", "Artist"),
    ("administrator", "Administrator"),
]


class CustomUser(AbstractUser):
    role = models.CharField(
        "Role", choices=ROLE_CHOICES, max_length=50, null=True, blank=True
    )
    image = models.ImageField("Image", upload_to="users/images", null=True, blank=True)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        if self.username:
            return self.username
        else:
            return self.email

    def save(self, *args, **kwargs):
        super(CustomUser, self).save()
        """reduce image size before upload to server"""
        if self.image:
            basewidth = 350
            img = Image.open(self.image)
            wpercent = basewidth / float(img.size[0])
            hsize = int((float(img.size[1]) * float(wpercent)))
            img = img.resize((basewidth, hsize), Image.ANTIALIAS)
            img.save(self.image.path)

    @property
    def is_last_login_updated(self):
        if self.last_login is not None:
            return self.last_login > timezone.now() - timezone.timedelta(seconds=1)
        return False


class AuthToken(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    token = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def is_expired(self):
        return timezone.now() > self.expires_at

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.contrib.auth.models import Permission
from django.db.models import Q
from cards.models import NFCCard

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):

    def save(self, commit=True):
        user = super().save(commit=False)
        role = self.cleaned_data["role"]
        if role == "superuser":
            user.is_staff = True
            user.is_superuser = True
            user.save()

        if commit:
            user.save()
        return user

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email:
            match = User.objects.filter(email=email)
            if match:
                raise forms.ValidationError("This email address is already in use")
            return email


class CustomUserChangeForm(UserChangeForm):

    def save(self, commit=True):
        user = super().save(commit=False)
        role = self.cleaned_data["role"]
        if role == "superuser":
            user.is_staff = True
            user.is_superuser = True
            user.save()

        if commit:
            user.save()
        return user

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email:
            match = User.objects.filter(email=email).exclude(id=self.instance.pk)
            if match:
                raise forms.ValidationError("This email address is already in use")
            return email


class UserDetailChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email:
            match = User.objects.filter(email=email).exclude(id=self.instance.pk)
            if match:
                raise forms.ValidationError("This email address is already in use")
            return email


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "User Name Or Email"})
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
    )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username is not None and password:
            self.user_cache = authenticate(
                self.request, username=username, password=password
            )
            if self.user_cache is None:
                try:
                    user = User.objects.get(
                        Q(username__iexact=username) | Q(email__iexact=username)
                    )
                except User.DoesNotExist:
                    user = None
                if user is not None:
                    if not user.is_active:
                        self.confirm_login_allowed(user)
                    else:
                        raise self.get_invalid_login_error()
                else:
                    raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            error = "The account is closed, please contact us for more details."
            raise forms.ValidationError(error)


class RegisterForm(UserCreationForm):
    def clean_email(self):
        email = self.cleaned_data["email"]
        if email:
            match = User.objects.filter(email=email)
            if match:
                raise forms.ValidationError("This email address is already in use")
            return email

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields["email"].required = True

    class Meta:
        model = User
        fields = ("email", "username")

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView
from django.http import HttpResponseRedirect
from .forms import CustomLoginForm, RegisterForm, UserDetailChangeForm
from .models import AuthToken
from .utils import create_token


class UserHomeView(LoginRequiredMixin, DetailView):
    """User Profile Page"""

    template_name = "user/home.html"

    def get_object(self):
        return self.request.user


class UserUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """User Profile Edit Page"""

    form_class = UserDetailChangeForm
    template_name = "user/user_edit.html"
    success_url = reverse_lazy("users:user_profile")
    success_message = "Details successfully updated"

    def get_object(self):
        return self.request.user


class RegisterView(SuccessMessageMixin, CreateView):
    template_name = "registration/register.html"
    #success_url = reverse_lazy("users:user_profile")
    form_class = RegisterForm
    success_message = "Your profile was created successfully"

    def form_valid(self, form):
        valid = super(RegisterView, self).form_valid(form)
        username, password = form.cleaned_data.get("username"), form.cleaned_data.get(
            "password1"
        )
        new_user = authenticate(username=username, password=password)
        login(self.request, new_user)
        return valid

    def get(self, request, *args, **kwargs):
        url_uuid = request.GET.get('uuid')
        uuid = request.COOKIES.get('uuid')
        if uuid:
            request.session['uuid'] = uuid
        elif url_uuid:
            request.session['uuid'] = url_uuid
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        uuid = self.request.session.get('uuid')
        if uuid:
            url = reverse("cards:link_new_card", args=[uuid])
        else:
            url = reverse('users:user_profile"')
        return  url


class CustomLoginView(LoginView):
    form_class = CustomLoginForm
    redirect_authenticated_user = True

    def form_valid(self, form):
        response = super().form_valid(form)
        token = create_token(self.request.user)
        self.request.session['auth_token'] = str(token)
        return response

    def get(self, request, *args, **kwargs):
        url_uuid = request.GET.get('uuid')
        uuid = request.COOKIES.get('uuid')
        if uuid:
            request.session['uuid'] = uuid
        elif url_uuid:
            request.session['uuid'] = url_uuid
        return super().get(request, *args, **kwargs)

    def get_redirect_url(self):
        uuid = self.request.session.get('uuid')
        if uuid:
            url = reverse("cards:link_new_card", args=[uuid])
        else:
            if self.request.user.is_staff or self.request.user.is_superuser:
                url = reverse("admin:index")
            else:
                url = reverse("cards:user_dashboard")
        return url


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        uuid = request.GET.get('uuid')
        if uuid:
            response = super().dispatch(request, *args, **kwargs)
            response.set_cookie('uuid', uuid, max_age=3600)  # Store for 1 hour
            return response

        token = request.session.get('auth_token')
        if token:
            AuthToken.objects.filter(token=token).delete()
        logout(request)
        return self.get_redirect_response(request)

    def get_redirect_response(self, request):
        uuid = request.COOKIES.get('uuid')
        if uuid:
            response = HttpResponseRedirect(reverse("users:login"))
            response.delete_cookie('uuid')
            return response
        else:
            return HttpResponseRedirect(reverse("cards:user_dashboard"))

templates/user/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load i18n %}
{% load custom_filters %}
{% block title %}
    {% trans 'Dashboard' %}
{% endblock %}
{% block content %}
<!-- Page Content  -->
<div class="contaner">
    <div class="row mt-3">
        <div class="col-md-6">
            <canvas id="total-views"></canvas>
        </div>
        <span class="d-none views_1">{{ hits_by_month.1  }}</span>
        <span class="d-none views_2">{{ hits_by_month.2  }}</span>
        <span class="d-none views_3">{{ hits_by_month.3  }}</span>
        <span class="d-none views_4">{{ hits_by_month.4  }}</span>
        <span class="d-none views_5">{{ hits_by_month.5  }}</span>
        <span class="d-none views_6">{{ hits_by_month.6  }}</span>
        <span class="d-none views_7">{{ hits_by_month.7  }}</span>
        <span class="d-none views_8">{{ hits_by_month.8  }}</span>
        <span class="d-none views_9">{{ hits_by_month.9  }}</span>
        <span class="d-none views_10">{{ hits_by_month.10  }}</span>
        <span class="d-none views_11">{{ hits_by_month.11  }}</span>
        <span class="d-none views_12">{{ hits_by_month.12  }}</span>
        <div class="col-md-6">
            <canvas id="total-views-pie"></canvas>
        </div>
    </div>
    <div class="line"></div>
    <div>
        <h3 class="text-center">Your Cards</h3>
        <div class="row">
            {% for card in user.user_cards.all %}
            {% get_hit_count for card as hits %}
            <div class="card col-md-4 mt-3 py-3 shadow-lg p-3 mb-5 bg-white rounded ">
                <div class="card-header">
                    <h4>{{ card }} <a href="{{ card.get_absolute_url }}" class="btn main-btn" target="_blank">View on Site</a></h4>
                </div>
                <div class="card-body">
                    <div class="p-1">
                        <a href="{% url 'cards:card_detail' card.uuid %}" class="btn main-btn mb-1"> 
                            Update Card
                        </a>
                    </div>
                    {% comment %}
                    <div class="p-1">
                        <a href="{% url 'cards:update_card' card.uuid card.pk %}" class="btn main-btn mb-1"> 
                            Update Card Main Info
                        </a>
                        <a href="{% url 'cards:update_business_card' card.uuid %}" class="btn main-btn mb-1"> 
                        Update Business Card
                        </a>
                        <a href="{% url 'cards:update_gallery' card.uuid %}" class="btn main-btn mb-1"> 
                        Update Gallery
                        </a>
                        <a href="{% url 'cards:update_redirect_url' card.uuid %}" class="btn main-btn mb-1"> 
                        Update Redirect URL
                        </a>
                        <a href="{% url 'cards:update_video_message' card.uuid %}" class="btn main-btn mb-1"> 
                        Update Video Message
                        </a>
                        <a href="{% url 'cards:update_product_viewer' card.uuid %}" class="btn main-btn mb-1"> 
                        Update Product Viewer
                        </a>
                        <a href="{% url 'cards:update_pdf_viewer' card.uuid %}" class="btn main-btn mb-1"> 
                        Update PDF Viewer
                        </a>
                        <a href="{% url 'cards:update_letter' card.uuid %}" class="btn main-btn mb-1"> 
                        Update Letter
                        </a>
                    </div>
                    <a href="{#{% url 'cards:set_password' card.uuid card.pk %}#}" class="btn main-btn mb-1"> 
                        {% if card.password %}Update Password {% else %}Set Password{% endif %}
                    </a>
                    {% endcomment %}
                    <p>Password: {% if card.password %}{{ card.password|mask_password }}{% else %}<span class="text-danger">{% trans 'not specified' %}</span>{% endif %}</p>
                    <p>
                        Views: <small class="ms-3"><i class="fa-regular fa-eye"></i> {{ hits }}</small>
                    </p>
                </div>
            </div>
            {% empty %}
            <p class="text-danger">No Cards Yet</p>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}


{% block extrajs %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="text/javascript" src="{% static 'js/dashboard.js' %}"></script>
{% endblock %}

templates/user/home.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load custom_filters %}
{% block title %}
Dashboard
{% endblock %}
{% block content %}



<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h3>Your Account Details</h3>
            <div class="card w-100 mt-3">
                <div class="card-header">
                    <a href="{% url 'users:account_update' %}" class="btn primary-btn">
                        <i class="fas fa-edit"></i>Edit
                    </a>
                </div>
                <div class="card-body">
                    <p>Username: {{ user.username }}</p>
                    <p>Email:
                        {% if user.email %}
                        {{ user.email }}
                        {% else %}
                        <span class="text-danger">not specified</span>
                        {% endif %}
                    </p>
                    <p>First name:
                        {% if user.first_name %}
                        {{ user.first_name }}
                        {% else %}
                        <span class="text-danger">not specified</span>
                        {% endif %}
                    </p>
                    <p>Last name:
                        {% if user.last_name %}
                        {{ user.last_name }}
                        {% else %}
                        <span class="text-danger">not specified</span>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/user/user_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Edit account
{% endblock %}
{% block content %}


<div class="container my-5 pt-5">
    <h2 class="mainTopic">Edit account</h2>
    <div class="card container">
        <div class="card-body">
            <form method="POST" class="mb-4">
                {% csrf_token %}
                {{ form|crispy }}<br>
                <p>Password:<br> <a class="form-control link-style text-primary"
                        href="{% url 'password_change' %}">Click to change password</a></p>
                <button class="btn main-btn" type="submit">Save</button>
                <a href="{% url 'users:user_profile' %}" class="btn main-btn">Back</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}